name: Publish NuGet Packages

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish NuGet Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
            7.0.x

      - name: Publish NuGet package
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: src/BingChat/BingChat.csproj
          PACKAGE_NAME: BingChat
          VERSION_FILE_PATH: src/BingChat/BingChat.csproj
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: Publish CLI
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: src/dotnet-bingchat/dotnet-bingchat.csproj
          PACKAGE_NAME: dotnet-bingchat
          VERSION_FILE_PATH: src/dotnet-bingchat/dotnet-bingchat.csproj
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}